services:
  - type: web
    name: kyn-aura
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JAVA_OPTS
        value: -Xms128m -Xmx384m
